[package]
name = "sumer-driver"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sumer-span = { workspace = true }
sumer-diagnostics = { workspace = true }
sumer-lexer = { workspace = true }
sumer-ast = { workspace = true }
sumer-parser = { workspace = true }
sumer-sema = { workspace = true }
