[package]
name = "sumer-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "sumer"
path = "src/main.rs"

[dependencies]
sumer-span = { workspace = true }
sumer-ast = { workspace = true }
sumer-diagnostics = { workspace = true }
sumer-driver = { workspace = true }
